### ISSUE TITLE
taskd hangs on TLS handshake

### ISSUE THREAD

**Issue by yzhou61** [GothenburgBitFactory/taskserver#158]
When this happens I need to kill -9 and restart the server. Here's the backtrace:

```
#0  0x00007f172db8d81d in __libc_recv (fd=6, buf=0x27c1bdb, n=5, flags=0)
    at ../sysdeps/unix/sysv/linux/x86_64/recv.c:28
#1  0x00007f172dfcbd6e in _gnutls_stream_read (ms=0x7ffd03e5edac, pull_func=<optimized out>, size=5, 
    bufel=<synthetic pointer>, session=0x27b4aa0) at gnutls_buffers.c:344
#2  _gnutls_read (ms=0x7ffd03e5edac, pull_func=<optimized out>, size=5, bufel=<synthetic pointer>, 
    session=0x27b4aa0) at gnutls_buffers.c:424
#3  _gnutls_io_read_buffered (session=session@entry=0x27b4aa0, total=5, recv_type=recv_type@entry=4294967295, 
    ms=0x7ffd03e5edac) at gnutls_buffers.c:580
#4  0x00007f172dfc627f in recv_headers (ms=<optimized out>, record=0x7ffd03e5ee00, 
    htype=GNUTLS_HANDSHAKE_CLIENT_HELLO, type=GNUTLS_HANDSHAKE, record_params=0x27c0650, session=0x27b4aa0)
    at gnutls_record.c:1028
#5  _gnutls_recv_in_buffers (session=session@entry=0x27b4aa0, type=type@entry=GNUTLS_HANDSHAKE, 
    htype=htype@entry=GNUTLS_HANDSHAKE_CLIENT_HELLO, ms=ms@entry=0) at gnutls_record.c:1156
#6  0x00007f172dfcd150 in _gnutls_handshake_io_recv_int (session=session@entry=0x27b4aa0, 
    htype=htype@entry=GNUTLS_HANDSHAKE_CLIENT_HELLO, hsk=hsk@entry=0x7ffd03e5ef20, optional=optional@entry=0)
    at gnutls_buffers.c:1406
#7  0x00007f172dfcfd0c in _gnutls_recv_handshake (session=session@entry=0x27b4aa0, 
    type=type@entry=GNUTLS_HANDSHAKE_CLIENT_HELLO, optional=optional@entry=0, buf=buf@entry=0x0)
    at gnutls_handshake.c:1437
#8  0x00007f172dfd365b in handshake_server (session=0x27b4aa0) at gnutls_handshake.c:3118
#9  gnutls_handshake (session=0x27b4aa0) at gnutls_handshake.c:2586
#10 0x00000000004893cf in TLSTransaction::init(TLSServer&) ()
#11 0x0000000000488e8c in TLSServer::accept(TLSTransaction&) ()
#12 0x0000000000477622 in Server::beginServer() ()
#13 0x0000000000467bf2 in command_server(Database&) ()
#14 0x000000000044d39e in main ()
```

**Comment by sebu06** [comment]
Hi,
I also had this issue. I had a client with an expired TLS certificate. After updating the certificate, the error seems to be gone (before I had to restart the server 1-2 times a day, now it is running since 5 days without problems).

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
